development: &dev
  adapter: postgresql
  encoding: unicode
  database: ls_development
  pool: 5
  username: postgres
  password:

test: &test
  <<: *dev
  database: ls_test

production:
  <<: *dev
  database: ls_production

cucumber:
  <<: *test
